# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'AcronymsViper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AcronymsViper
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'AlamofireObjectMapper', '~> 6.2.0'
  pod 'SwiftyJSON', '~> 4.0'

  target 'AcronymsViperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AcronymsViperUITests' do
    # Pods for testing
  end

end
